#pragma once
#include <string>
const int numOfProps = 35;
std::string mapLayout[numOfProps]{
	"                                   ",
	"                                   ",
	"                                   ",
	"                                   ",
	"       sbbbbb       oxx   xx       ",
	"                                   ",
	"                                   ",
	"          xx        xxx   xx       ",
	"          xx        x x   xx       ",
	"          xx              xx       ",
	"                                   ",
	"       b  xx        xxx   bb       ",
	"       b  xx                       ",
	"          xx        x x   xx       ",
	"          xx        xxx   xx       ",
	"                          xx       ",
	"                                   ",
	"       b  xx   s     xx   xx       ",
	"       b  xx        xxx   xx       ",
	"                                   ",
	"       b  xx        xxx   bb       ",
	"       b  xx         xx            ",
	"       b  xx   b    xxx   xx       ",
	"       b  xx         xx   xx       ",
	"                    xxx   xx       ",
	"       b  xx         xx   xx       ",
	"       b  xx              xx       ",
	"       b  xx        xxx   xx       ",	
	"          xx         xx   xx       ",
	"       s  xx        xxx   xx       ",
	"                                   ",
	"       b  xx        xxx   bb       ",
	"                                   ",
	"                                   ",
	"                                   "
};