#pragma once
#include <string>
const int numOfProps = 35;
const int numOfEnemies = 20;

std::string mapLayout[numOfProps]{
	"                                   ",
	"                                   ",
	"                                   ",
	"                                   ",
	"       sbbbbb       oxx   xx       ",
	"                                   ",
	"                                   ",
	"          xx        xxx   xx       ",
	"          xx        x x   xx       ",
	"          xx              xx       ",
	"                                   ",
	"       b  xx        xxx   bb       ",
	"       b  xx                       ",
	"          xx        x x   xx       ",
	"          xx        xxx   xx       ",
	"                          xx       ",
	"                                   ",
	"       b  xx   s    o x   xx       ",
	"       b  xx        xxx   xx       ",
	"                                   ",
	"       b  xx        xxx   bb       ",
	"       b  xx         xx            ",
	"       b  xx   b    o x   xx       ",
	"       b  xx         xx    o       ",
	"                    xxx   xx       ",
	"       b  xx         xx   xx       ",
	"       b  xx    o         xx       ",
	"       b  xx        xxx   xx       ",	
	"          xx         xx   xx       ",
	"       s  xx        xxx   xx       ",
	"                                   ",
	"       b  xx        xxx   bb       ",
	"                                   ",
	"                                   ",
	"                                   "
};
std::string mapDungeonLayout[numOfProps]{
	"                                   ",
	"                                   ",
	"                                   ",
	"                  b                ",
	"                          b        ",
	"          b                        ",
	"                                   ",
	"    wwwwwwwwxswwwwwwwxswwwwwwwwww  ",
	"                                w  ",
	"      wwwwwwwxswwwwwwwxswwwww   w  ",
	"      w                     w   w  ",
	"      w                     x   w  ",
	"      x    wwwwwwwwwwwww    s   w  ",
	"      s    w           w    w   w  ",
	"      w    w           w    w   w  ",
	"      w    s    w      w    w   w  ",
	"      w    x    w      w    w   x  ",
	"      w    w    w      w    w   s  ",
	"      w    w    w      w    w   w  ",
	"      w    w    w      w    w   w  ",
	"      x    w    w      w    x   w  ",
	"      s    w    w      w    s   w  ",
	"      w    w    w      w    w   w  ",
	"      w    w    w      w    w   w  ",
	"      w    s    w      x    w   w  ",
	"      w    x    w      s    w   w  ",
	"      w    w    w      w    w   w  ",
	"      w    w    wwwwwwww    w   x  ",
	"      w    w                w   s  ",
	"      x    w                x   w  ",
	"      s    wwwxswwwwwwwwwwwws   w  ",
	"      w                         w  ",
	"      w                         w  ",
	"      wwwwwwxswwwwwwwwwwwwwwwxsww  ",
	"                                   "
};


std::string mapLayoutEnemies[numOfProps]{
	"                                   ",
	"                                   ",
	"                                   ",
	"                                   ",
	"                                   ",
	"                                   ",
	"                                   ",
	"          xx        xxx   xx       ",
	"          xx        x x   xx       ",
	"          xx              xx       ",
	"                                   ",
	"       b  xx        xxx   bb       ",
	"                                   ",
	"          xx        x x   xx       ",
	"          xx        xxx   xx       ",
	"                          xx       ",
	"                                   ",
	"       b  xx   s    o x   xx       ",
	"       b  xx        xxx   xx       ",
	"                                   ",
	"       b  xx        xxx   bb       ",
	"       b  xx         xx            ",
	"                                   ",
	"       b  xx         xx    o       ",
	"                    xxx   xx       ",
	"       b  xx         xx   xx       ",
	"       b  xx    o         xx       ",
	"                                   ",
	"                                   ",
	"       s  xx        xxx   xx       ",
	"                                   ",
	"                                   ",
	"                                   ",
	"                                   ",
	"                                   "
};
