#pragma once
#include <string>
const int numOfProps = 35;
std::string mapLayout[numOfProps]{
	"                                   ",
	"                                   ",
	"  x  xooooxxx   xx  xxx        xx  ",
	"                    xxx   xx   xx  ",
	"                          xx   xx  ",
	"   xo  s  xx        xxx   xx   xx  ",
	"                                   ",
	"   xo     xx        xxx   xx   xx  ",
	"          xx        xxx   xx   xx  ",
	"   xo     xx              xx   xx  ",
	"                                   ",
	"   xo  s  xx        xxx   xx   xx  ",
	"   xo  b  xx               x   xx  ",
	"   xo     xx        xbx   xx   xx  ",
	"   xo     xx        xxx   xx   xx  ",
	"   bo                     xx   xx  ",
	"                                   ",
	"   xo  s  xx        xxx   xx   xx  ",
	"   xo  s  xx        xxx   xx   xx  ",
	"                                   ",
	"   xo  s  xx        xxx        xx  ",
	"   xo  s  xx        xxx   xx   xx  ",
	"   xo  s  xx        xxx   xx       ",
	"   xo  s  xx        xxx   xx   xx  ",
	"                    xxx   xx   xx  ",
	"   xo  s  xx        xxx   xx       ",
	"   xo  s  xx              xx   xx  ",
	"       s  xx        xxx   xx   xx  ",	
	"   xo     xx        xxx   xx       ",
	"   xo  s  xx        xxx   xx       ",
	"                                   ",
	"   xo  s  xx        xxx   xx       ",
	"   xo     xx        xxx   xx       ",
	"   xo  s  xx        xxx   xx       ",
	"                                   "
};